[package]
name = "micrors"
description = "Library to get started with microcontroller development."
version = "0.0.0"
authors = ["wilypomegranate <wilypomegranate@users.noreply.github.com>"]
homepage = "https://github.com/wilypomegranate/micrors"
edition = "2018"
license = "MPL-2.0"
